import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_JP, Inter } from "next/font/google";
import Footer from "@/components/molecules/footer";
import Header from "@/components/molecules/header";
import StoreProvider from "@/store/store-provider";

const notoSanJp = Noto_Sans_JP({
  variable: "--font-noto-san-jp"
})

const inter = Inter({
  variable: "--font-inter"
})

export const metadata: Metadata = {
  title: "Arent Health App - Tran Cong Luc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSanJp.variable} ${inter.variable} antialiased`}
      >
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
