import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const notoSanJp = Noto_Sans_JP({
  variable: "--font-noto-san-jp"
})

export const metadata: Metadata = {
  title: "Arent Health App - Tran Cong Luc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSanJp.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
